// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEjg_jp6n-x0L6rVmCi_6_YYMwYIqYYdQ',
    appId: '1:324888075239:web:be61fa813dfd60267d7b42',
    messagingSenderId: '324888075239',
    projectId: 'safeapp-8e1ba',
    authDomain: 'safeapp-8e1ba.firebaseapp.com',
    storageBucket: 'safeapp-8e1ba.firebasestorage.app',
    measurementId: 'G-8BQP7QLM2Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1FsoKFoavJ1UcvJr_KYDMOJPdPu5ISTg',
    appId: '1:324888075239:android:3aa088397e39e0b77d7b42',
    messagingSenderId: '324888075239',
    projectId: 'safeapp-8e1ba',
    storageBucket: 'safeapp-8e1ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBxt1TBSxUKA2AG_aGd-2KIsAbMUyuC8U',
    appId: '1:324888075239:ios:a56d3848b19efe137d7b42',
    messagingSenderId: '324888075239',
    projectId: 'safeapp-8e1ba',
    storageBucket: 'safeapp-8e1ba.firebasestorage.app',
    iosBundleId: 'com.example.hotelbooking',
  );
}
